# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/myapp main.go"
  bin = "tmp/myapp"
  full_bin = "./tmp/myapp"
  include_ext = ["go", "yaml"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true
